> # **a_tensor_initialization.py**

In [142]:
import torch

t1 = torch.Tensor([1 ,2 ,3], device='cpu') # 데이터 타입이 float64로만 선언되는 tensor형 변수 t1 선언하기. 그리고 tensor를 cpu에 올리기
print(t1.dtype) # 변수 t1의 데이터 타입 출력하기
print(t1.device) # 변수 t1이 어디에 올려져 있는지 출력
print(t1.requires_grad) # tensor의 기울기 저장 여부 출력. 기울기 사용처는 자동 미분이 있음
print(t1.size()) # tensor의 크기 출력
print(t1.shape) # tensor의 크기 출력 ( t1.size() == t1.shape )

"""
t100 = torch.tensor([1, 2, '3'])
print(t100)                      # tensor는 반드시 한 타입의 데이터로만 정의되므로 error.
a100 = torch.tensor(['a', 'b'])
print(a100)                      # tensor는 숫자 데이터만 들어갈 수 있으므로 error
"""

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda')) - t1_cuda를 gpu 'cuda'에 올려놓음
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

print("#" * 50, 1)

# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu') # 입력된 데이터에 따라 타입이 변하는 tensor형 변수 t2선언하기. 그리고 cpu에 올리기
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

print("#" * 50, 2)
 
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0 
print(a1.shape, a1.ndim)             # ndim : tensor가 몇차원 데이터를 저장하고 있는지 출력함

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],           # 4차원 size가 일정해야 하는데, 한쪽은 2, 한쪽은 3이라 오류 발생함
    [[[1, 2, 3], [4, 5]]],    
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])


#한쪽 차원을 축소시키거나, 한쪽 차원을 추가시키면 오류가 해결됨.
# a11 = torch.tensor([
#     [[[1, 2, 3], [4, 5, 6]]],           
#     [[[1, 2, 3], [4, 5, 6]]],
#     [[[1, 2, 3], [4, 5, 6]]],
#     [[[1, 2, 3], [4, 5, 6]]],
# ])
# print(a11.shape, a11.ndim) : 에러 없음

# a12 = torch.tensor([                
#     [[[1, 2], [4, 5]]],           
#     [[[1, 2], [4, 5]]],
#     [[[1, 2], [4, 5]]],
#     [[[1, 2], [4, 5]]],
# ])
# print(a12.shape, a12.ndim) : 에러 없음




torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1
torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

> # [고찰]
> tensor는 문자 데이터를 담지 못하므로 문자 데이터를 아스키코드 등으로 정수화 시킨 후 담을 수 있을 것 같음. <br>
> dict 타입을 텐서화 시키려면 데이터 값만 tensor화 한 상태로 새로운 dict을 만들면 된다는 것을 찾아서 알 수 있었음. <br>
> tensor는 차원의 size를 정확히 지켜야 한다는 것을 알게 되었음. <br>

> # **b_tensor_initialization_copy.py**

In [143]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1) # 실수형 타입 tensor로 변환하기 때문에 안의 데이터도 실수형으로 변환됨

l2 = [1, 2, 3]
t2 = torch.tensor(l2) # 입력한 값에 따라 데이터의 타입이 바뀜.

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) # torch.from_numpy()와 동일. 입력한 값에 따라 데이터 타입이 변경됨.


# torch.from_numpy 역시 torch.as_tensor와 동일하게 작동하는 것을 알 수 있음.
# l100 = np.array([1, 3, 5])
# print(l100)
# t100 = torch.from_numpy(l100)
# print(t100)
# l100[0] = 0
# print(l100)
# print(t100)


l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3) # 리스트 형태의 데이터를 이용하여 tensor를 생성했을 경우 이전 데이터를 참조, 생성방법과 상관없이 이전 데이터를 변경하였더라도 tensor가 변경되지 않음.


print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6) # ndarray형태의 데이터를 이용하여 tensor를 생성했을 경우, torch.as_tensor / torch.from_numpy를 사용하였다면 이전 데이터와 공유하게 되며,
          # 이를 변경하였을 때 tensor 또한 변경됨.


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


> # [고찰]
> ndarray 형태를 as_tensor / from_numpy를 사용하여 tensor화 하면 참조한다고 알게 되었는데, 참조를 통한 tensor화를 사용할까 고민하게 되었음. 데이터의 양이 매우 많기 때문에 복사를 통한 tensor생성보단 참조가 더 효율적이라고 생각하게 되었음.   

> # **c_tensor_initialization_constant_values.py**

In [144]:
import torch

t1 = torch.ones(size=(5,))  # or torch.ones(5) 5 크기의 1로 초기화된 1차원 tensor 생성 ( 실수 값으로 초기화함 )
t1_like = torch.ones_like(input=t1) # t1와 동일한 크기의 1로 초기화된 1차원 tensor 생성
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])


# 여러 차원의 tensor 제작에도 사용할 수 있다는 것을 알 수 있음.
# t100 = torch.ones(size=(3,2))  
# print(t100)


t2 = torch.zeros(size=(6,))  # or torch.zeros(6) 6 크기의 0으로 초기화된 1차원 tensor 생성
t2_like = torch.zeros_like(input=t2) # t2와 동일한 크기의 0으로 초기화된 1차원 tensor 생성
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4) 4 크기의 빈 공간으로 초기화된 1차원 tensor 생성
t3_like = torch.empty_like(input=t3) # t3와 동일한 크기의 빈 공간으로 초기화된 1차원 tensor 생성
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3) # 3 크기의 대각성분만 1인 2차원 tensor 생성
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0.0000, 1.8750, 5.0000, 5.0000])
tensor([0.0000, 1.8750, 3.0000, 4.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


> # [고찰]
> 여러 크기의 tensor에 대해서 적용할 수 있다는 것을 알 수 있었음.<br>
> empty는 빈 공간으로 초기화하기 때문에, 저장공간에 남아있는 데이터가 출력될 수 있다는 것을 알 수 있었음.<br>
> 그래서 매번 실행할 때마다 값이 다르게 나왔음.

> # **d_tensor_initialization_random_values.py**

In [145]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))  # low~high 사이의 정수값을 동일한 확률로 랜덤 생성해서 size 크기만한 tensor 생성
print(t1)

t2 = torch.rand(size=(1, 3))                      # 0~1사이의 실수를 동일한 확률로 랜덤으로 생성하여 size 크기만한 tensor 생성
print(t2)

t3 = torch.randn(size=(1, 3))                     # 분산이 1이고 평균이 0인 표준정규분포 값 중에 랜덤으로 생성해서 tensor 생성
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))# 평균과 표준편차가 주어진 정규분포에서 값을 랜덤으로 생성해서 tensor 생성
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)  # 시작값과 종료값 사이에 일정한 간격으로 구성된 값들을 step값 만큼 생성하여 tensor 생성
print(t5)

t6 = torch.arange(5)                              # 0~4사이의 정수가 순서대로 배정된 tensor 생성. range 개념과 유사함.
print(t6)


# t100 = torch.randperm(7)                           -> tensor([6, 3, 0, 2, 5, 1, 4]) 0~입력값까지의 정수값을 한번씩 나오게 랜덤으로 생성


print("#" * 30)

torch.manual_seed(1729)                           # random seed(동일한 난수)를 고정. 같은 결과가 나오게 만들어줌.
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)


tensor([[17, 12]])
tensor([[0.0453, 0.5035, 0.9978]])
tensor([[0.7419, 0.5923, 0.2908]])
tensor([[ 9.2270, 10.0961],
        [ 9.4067,  9.5878],
        [10.0763, 11.1161]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


> # [고찰]
> torch.randperm()도 랜덤값을 출력하는 함수라는 것을 알게 되었음.

> # **e_tensor_type_conversion.py**

In [146]:
import torch

a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16) # tensor의 데이터타입을 임의로 변경함.
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20. # *torch.rand() * a는 0~a 범위 중 랜덤으로 값을 추출함.
print(c)


# *a는 여러 랜덤함수에도 적용됨.
# t1000 = torch.randint(low=0, high=10, size=(3, 3)) * 2
# print(t1000)
# t1001 = torch.randn(size=(3, 3)) * 2                  
# print(t1001)
# t1002 = torch.linspace(start=1.0, end=10.0, steps=5) * 2
# print(t1002)

d = b.to(torch.int32) # tensor의 데이터타입을 int16 -> int32로 변경함.
print(d)

double_d = torch.ones(10, 2, dtype=torch.double) # tensor의 데이터타입을 실수로 바꿈
short_e = torch.tensor([[1, 2]], dtype=torch.short) # tensor의 데이터타입을 정수로 바꿈

double_d = torch.zeros(10, 2).double() # tensor의 데이터타입을 실수로 바꿈
short_e = torch.ones(10, 2).short() # tensor의 데이터타입을 정수로 바꿈


#형변환 함수는 대각행렬함수에 적용할 수 있는지 확인.
# qq = torch.eye(3).short()
# print(qq)
# qq = qq.to(torch.float64)
# print(qq)
# qq = torch.eye(3, dtype=torch.int16)
# print(qq)


double_d = torch.zeros(10, 2).to(torch.double) # tensor의 데이터타입을 실수로 바꿈
short_e = torch.ones(10, 2).to(dtype=torch.short) # tensor의 데이터타입을 정수로 바꿈

double_d = torch.zeros(10, 2).type(torch.double) # tensor의 데이터타입을 실수로 바꿈
short_e = torch.ones(10, 2). type(dtype=torch.short) # tensor의 데이터타입을 정수로 바꿈

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


> # [고찰]
> 형변환은 대부분 잘 적용되는 것을 알 수 있었고, '*값'도 역시 대부분 잘 적용된다는 것을 알 수 있었음.

> # **f.tensor_operations.py**

In [147]:
# element-wise operations는 각 요소에 대해 연산하는 것을 의미하며, add(), sub(), mul(), div() 등이 있음.
import torch

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2) # torch.add(), "+"를 통해 같은 위치의 데이터를 서로 더해줌.
t4 = t1 + t2
print(t3)
print(t4)


# t100 = torch.ones(3, 3)
# t101 = torch.ones_like(t100)
# print(t100 % t101)            : %연산에 대해서도 잘 적용됨
# print(t100 // t101)           : //연산에 대해서도 잘 적용됨

print("#" * 30)

t5 = torch.sub(t1, t2) # torch.sub(), '-'연산자를 통해 같은 위치의 데이터를 서로 빼줌.
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2) # torch.mul(), '*' 연산자를 통해 같은 위치의 데이터를 서로 곱해줌.
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2) # torch.div(), '/'연산자를 통해 같은 위치의 데이터를 서로 나눠줌.
t10 = t1 / t2
print(t9)
print(t10)


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


> # [고찰]
> 몫 연산, 나머지 연산에 대해서도 element-wise operations이 잘 적용된다는 것을 알 수 있었다.

> # **g_tensor_operations_mm.py**

In [148]:
import torch

t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1]) # 두 텐서의 내적?값이 출력됨. size는 torch.tensor(3)처럼 빈 공간이라고 출력됨.
)
print(t1, t1.size())


#torch.dot()은 1차원 tensor만 가능
# t100 = torch.dot(torch.tensor([[1,2], [3, 4]]), torch.tensor([[5,2], [3,3]])) -> error 
# print(t100, t100.size())


t2 = torch.randn(2, 3) 
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3) # 2차원 행렬곱 수행. 단, 두 행렬의 size가 맞아야함.
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6) # 3차원 행렬곱 수행. 첫번째 차원을 제외하고 행렬곱 수행. 단, 첫 행렬(batch)을 제외한 두 행렬의 size가 맞아야함.
print(t7.size())

tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


> # [고찰]
> .

> # **h_tensor_operations_matmul.py**

In [149]:
import torch
# torch.matmul()은 데이터의 종류에 따라 dot, mm, bmm 처럼 이용할 수 있고, broadcasting을 지원함.
# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([]) 

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


> # [고찰]
> .

> # **i_tensor_broadcasting.py**

In [150]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0]) # [1.0, 2.0, 3.0] * [2.0, 2.0, 2.0]
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])# t3.size() = (3, 2) / t4.size() = (  2)
t4 = torch.tensor([4, 5])                    # [[0,1], [2, 4], [10, 10]] - [[4, 5], [4, 5], [4, 5]]
print(t3 - t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])     # t5.size() = (2, 2)
print(t5 + 2.0)  # t5.add(2.0)              # [[1., 2.], [3., 4.]] + [[2.0, 2.0], [2.0, 2.0]]
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)


# t100 = torch.ones(3, 3)
# t101 = torch.ones(1, 1)
# print(t101 % t100)                          : %연산, //연산에 대해서도 broadcasting이 잘 적용됨.
# t00 = torch.ones(3, 3)
# t01 = torch.ones(1, 1)
# print(t00 // t01)


print("#" * 50, 3)


def normalize(x):                           # 데이터들의 범위를 한정시키기 위해 사용됨. 가령 0~256범위의 값을 가지는 이미지 데이터값을 0~1으로 변경하기 위해 사용
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)   # torch.pow()는 입력한 tensor값의 제곱된 값을 반환하게 됨.
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])


tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

> # [고찰]
> 파이썬에서 사용가능한 모든 연산에 대해 broadcasting이 잘 적용된다는 것을 알 수 있었음.

> # **j_tensor_indexing_slicing.py**

In [151]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])


# t01 = torch.as_tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print(t01)
# print(t01[:, ::2])                                     : 일정한 간격으로 slicing 할 수 있음.


print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

# tensor도 python list처럼 인덱싱, 슬라이싱이 동일하나는 것을 알 수 있음.

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


> # [고찰]
> 일정한 간격으로 slicing하는 것도 가능하다는 것을 알 수 있었음. <br>
> slicing 기능을 잘 사용하는 것이 더 좋은 모듈을 만드는 키라고 생각함.

> # **k_tensor_reshaping.py**

In [152]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]]) #view()는 contiguous인 경우에 가능하며, reshape()는 contiguous인 경우 이전 데이터를 참조함.
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)
# print(t1.contiguous) # -> true

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,) #squeeze()는 차원을 줄임. copy 형식

 
# t106 = torch.ones(1, 3, 2)
# t107 = t106.squeeze() # -> torch.Size(3, 2) : 차원 size가 1인 차원만 줄임.

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)


# t108 = t106.squeeze(1) # -> torch.Size(1, 3, 2)


print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1) #unsqueeze()는 차원을 늘림. copy 형식
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,) #flatten()은 다차원을 1차원으로 변형. 한쌍을 제외한 모든  괄호를 제거한다고 해석할 수 있음.

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1) #start_dim값에 해당하는 차원부터 1차원으로 변형해줌.

print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5]) : 차원은 유지하면서, size를 변형하는 함수.
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2) transpose()는 행과 열을 cross해줌.

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


> # [고찰]
> squeeze, unsqueeze는 size가 1인 차원만 줄이며, 1이 아닌 차원을 지정해도 줄이지 못한다는 것을 알 수 있었음.

> # **l_tensor_concat.py**

In [153]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1) #concat() / cat()은 특정 차원을 stack구조처럼 쌓아주는 함수임. 단 쌓으려는 차원을 제외한 나머지 차원은 같아야 함.
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

> # [고찰]
> cat은 데이터 샘플의 수를 늘릴 때 주로 사용한다는 것을 알게 되었음.

> # **m_tensor_stacking.py**

In [154]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0) #cat()과 달리 새로운 차원을 생성해 쌓아주는 형식임. stack = unsqueeze + cat
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))


# t101 = torch.tensor([1, 2, 3])
# t102 = torch.ones(1)
# t103 = torch.stack((t101, t102), dim=0) -> stack 역시 나머지 차원의 크기가 같아야함.

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True


torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


> # [고찰]
> stack은 batch 처리에 자주 사용된다는 것을 알게 되었음. 


> # **n_tensor_vstack_hstack.py**

In [155]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))  # vstack은 수직으로 쌓음.
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11)) # hstack은 수평으로 쌓음.
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])

# cat VS vstack / cat VS hstack
# t009 = torch.tensor([[[1], [2], [3]]])
# t0010 = t009 +3

# t0011 = torch.hstack((t009, t0010))
# t0012 = torch.cat((t009, t0010), dim=1)
# print(t0011.equal(t0012))                  -> True

# t0013 = torch.vstack((t009, t0010))
# t0014 = torch.cat((t009, t0010), dim=0)
# print(t0013.equal(t0014))                  -> True

# print(torch.cat((t009, t0010), dim=2))


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


> # [고찰]
> vstack, hstack은 cat과 유사해 2차원 tensor까진 대체할 수 있지만, 3차원이상부턴 cat을 사용하지 않으면 불편하기 때문에 cat을 더 자주 쓸 것 같다고 생각함. 또한 딥러닝은 데이터가 주로 3차원이 많이 보이기 때문에 딥러닝 모델 학습에선 cat을 좀 더 쓸 것 같음.

> # **숙제 후기**
> 텐서를 공부하면서 데이터 전처리 함수가 잘 적용되는 array라고 생각하게 되었음. 그래서 array를 잘 사용해봐서 학습하는데 큰 어려움은 없었음. 어려웠던 점은 2차원 배열과 3차원 이상의 배열의 시각적인 차이점이 괄호밖에 없다는 것이었음. 직관적으로 한번에 "이건 몇차원이네"라고 바로 생각하기 어려웠고, stack 결과물을 예상하는데 시간이 걸렸음. 그래서 이 어려움을 해결하는게 딥러닝 공부에 큰 관건이 될 것이라고 생각함.
> 가장 기억에 남는 함수는 unsqueeze / squeeze인것 같음. 뒤에 나온 bike_sharing_data를 보면서 약 17000개의 데이터를 unsqueeze함수 하나로 간단하게 전처리 한게 눈에 익었음. 